# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
desc "Upload release apk on firebase app distribution"
lane :distributeReleaseApk do
  gradle(    task: "assemble",
          build_type: "Release"  )
  firebase_app_distribution(
          app: "1:783458988956:android:f55c2fcbd20e8db0134e59",
# this is app id we can collect it from firebase → Project overview → Project #Settings →General
          firebase_cli_token:"1//0gGgFtLBXlZbaCgYIARAAGBASNwF-L9Ir213kJArDFcfs-pzu7NYHJiWGNxQKAQo0kj9_3p0WZmQv1jlDV0rZH8F389gQAFpj6_U"
          release_notes_file: "fastlane/release-notes.txt",
#create release-notes.txt file
          groups_file: "fastlane/group.txt"
#create group.txt file to mention testers
  )
end

